material_params:
  rho: 2700
  lam: 3.8e8
  mu: 1.23e9
  nu: 6.52e7
  J: 1.71e5
  lam_c: 8.48e3
  mu_c: 2.15e10
  nu_c: 2.15e10

source_params:
  type: "Ricker"
  f0: 3
  factor: 1.0e+10
  tshift: 0.0
  angle: 0.0
  f: 1
  fc: 1

ft_params:
  dt: 0.003
  N: 1000
  oversample_rate: 40

seismogram_locations:
  - [500.0, 500.0]
  - [833.3, 833.3]
  - [1166.7, 1166.7]
  - [1500.0, 1500.0]
